DROP DATABASE IF EXISTS Restaurante;

DROP TABLE IF EXISTS cliente;

DROP TABLE IF EXISTS prato;

DROP TABLE IF EXISTS fornecedor;

DROP TABLE IF EXISTS ingredientes;

DROP TABLE IF EXISTS usos;

DROP TABLE IF EXISTS venda;

DROP PROCEDURE IF EXISTS Reajuste;

DROP PROCEDURE IF EXISTS Sorteio;

DROP PROCEDURE IF EXISTS Estatistica;

DROP PROCEDURE IF EXISTS Gastar_pontos;