CREATE PROCEDURE IF NOT EXISTS Reajuste(IN percentual DOUBLE)
BEGIN
    UPDATE prato
    SET valor = valor + (valor * (percentual/100));
END;

CREATE PROCEDURE IF NOT EXISTS sorteio()
BEGIN

END;

CREATE PROCEDURE IF NOT EXISTS Estatisticas()
BEGIN

END;

CREATE PROCEDURE IF NOT EXISTS Gastar_pontos()
BEGIN

END;